version: 0.1.{build}
os: Visual Studio 2015

cache:
 - 'packages -> **\packages.config'

before_build:
  - nuget restore

build_script:
- cmd: '"%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe" /nologo /m /v:m /nr:false /flp:verbosity=detailed'

artifacts:
 - path: src\PowerBuild.NuGet\bin\**\*.nupkg
   name: Packages