version: 0.1.{build}
os: Visual Studio 2017
configuration: Release
cache:
 - 'packages -> **\packages.config'

before_build:
  - nuget restore

build:
  parallel: true
  verbosity: minimal

artifacts:
 - path: src\PowerBuild.NuGet\bin\$(configuration)\*.nupkg
   name: Packages
 - path: src\PowerBuild\bin\$(configuration)
   name: Binaries